cache:
  - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
    
platform:
  - Any CPU

configuration:
  - Debug
  - Release
  
matrix:
  fast_finish: true

before_build:
  - nuget restore
  
after_build:
  - 7z a OptiKey.zip %APPVEYOR_BUILD_FOLDER%\src\JuliusSweetland.OptiKey\bin\%configuration%\*
  
artifacts:
  - path: OptiKey.zip
    name: OptiKey